# Generated by Django 3.0.8 on 2020-09-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0002_auto_20200902_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
