# Generated by Django 3.0.8 on 2020-09-04 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0002_auto_20200904_1631'),
        ('QnA', '0003_auto_20200902_1708'),
    ]

    operations = [
    ]
