# Generated by Django 3.1 on 2020-09-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0005_auto_20200909_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_hit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
