# Generated by Django 3.0.8 on 2020-09-22 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0006_post_post_hit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('pub_date',), 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
