# Generated by Django 3.1 on 2020-08-11 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200811_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
    ]
