# Generated by Django 3.0.8 on 2020-09-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200812_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vespauser',
            name='email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vespauser',
            name='grade',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vespauser',
            name='major',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='vespauser',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vespauser',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vespauser',
            name='studentNumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vespauser',
            name='user_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vespauser',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
