# Generated by Django 3.1 on 2020-09-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200901_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vespauser',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
