# Generated by Django 3.1 on 2020-09-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200901_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vespauser',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
