# Generated by Django 3.0.8 on 2020-09-01 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200901_1126'),
        ('accounts', '0008_auto_20200901_1407'),
    ]

    operations = [
    ]
