# Generated by Django 3.0.8 on 2020-09-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200907_1458'),
        ('forum', '0002_auto_20200907_1358'),
    ]

    operations = [
    ]
