# Generated by Django 3.1.7 on 2021-07-24 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_comment_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='retweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.comment'),
        ),
    ]
