# Generated by Django 3.1 on 2020-09-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20200909_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_hit',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
