# Generated by Django 3.0.8 on 2020-09-22 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_post_post_hit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('pub_date',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
