# Generated by Django 3.1.7 on 2021-08-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vespaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('studentNumber', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('usertype', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ('username',),
            },
        ),
    ]
