# Generated by Django 3.1 on 2020-08-12 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200812_1056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='vespaUser',
        ),
    ]
