# Generated by Django 3.1 on 2020-10-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_id', models.CharField(max_length=20)),
                ('prob_name', models.CharField(max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('size_limit', models.IntegerField()),
                ('try_limit', models.IntegerField()),
                ('time_limit', models.FloatField()),
                ('eval', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'exam_problems',
                'ordering': ('prob_id',),
            },
        ),
        migrations.CreateModel(
            name='SubmissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ID', models.CharField(max_length=20)),
                ('client_number', models.CharField(max_length=20)),
                ('prob_ID', models.CharField(max_length=20)),
                ('prob_name', models.CharField(default='-', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField()),
                ('exec_time', models.FloatField()),
                ('code_size', models.IntegerField()),
                ('lang', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'exam_submissions',
                'ordering': ('-id',),
            },
        ),
    ]
