# Generated by Django 3.1 on 2020-10-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProblemModel',
            new_name='ExamProblemModel',
        ),
        migrations.RenameModel(
            old_name='SubmissionModel',
            new_name='ExamSubmissionModel',
        ),
    ]
