# Generated by Django 3.1 on 2020-08-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20200824_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.TextField(default='', verbose_name='AUTHOR'),
        ),
    ]
