# Generated by Django 3.1.7 on 2021-07-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemmodel',
            name='sample_data',
        ),
    ]
