# Generated by Django 3.1.7 on 2021-07-29 14:11

import assignment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_remove_problemmodel_sample_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemmodel',
            name='sample_data',
            field=models.FileField(null=True, upload_to=assignment.models.sample_data_upload_path),
        ),
    ]
