# Generated by Django 3.2.5 on 2021-08-19 11:37

import assignment.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20210819_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grademodel',
            name='grade_input',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/assignment', location='/opt/vespa/data/problems'), upload_to=assignment.models.grade_data_upload_path),
        ),
        migrations.AlterField(
            model_name='grademodel',
            name='grade_output',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/assignment', location='/opt/vespa/data/problems'), upload_to=assignment.models.grade_data_upload_path),
        ),
        migrations.AlterField(
            model_name='problemmodel',
            name='header_data',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/assignment', location='/opt/vespa/data/problems'), upload_to=assignment.models.header_data_upload_path),
        ),
        migrations.AlterField(
            model_name='problemmodel',
            name='sub_data',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/assignment', location='/opt/vespa/data/problems'), upload_to=assignment.models.sub_data_upload_path),
        ),
        migrations.AlterField(
            model_name='submissionmodel',
            name='sub_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/submission', location='/opt/vespa/data/submission'), upload_to=assignment.models.submission_upload_path),
        ),
    ]
