# Generated by Django 3.1 on 2020-09-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20200831_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=20)),
                ('prob_ID', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'submissions',
            },
        ),
        migrations.DeleteModel(
            name='UploadFileModel',
        ),
    ]
