# Generated by Django 3.1.7 on 2021-07-29 14:56

import assignment.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_problemmodel_sample_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionmodel',
            name='sub_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/submission', location='/Users/LeeJunYoung/Desktop/NESPA/data/submission'), upload_to=assignment.models.submission_upload_path),
        ),
    ]
