# Generated by Django 3.1.7 on 2021-07-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20210729_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissionmodel',
            old_name='user',
            new_name='client',
        ),
    ]
