# Generated by Django 3.1 on 2020-09-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_remove_submissionmodel_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionmodel',
            options={'ordering': ('-id',)},
        ),
    ]
