# Generated by Django 3.1 on 2020-09-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_problemmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemmodel',
            name='eval',
            field=models.CharField(default='TBD', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='prob_name',
            field=models.CharField(default='01', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='try_limit',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
