# Generated by Django 3.2.5 on 2021-07-30 04:07

import assignment.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_auto_20210730_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionmodel',
            name='sub_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/submission', location='/Users/yoojunhong/Desktop/NESPA/data/submission'), upload_to=assignment.models.submission_upload_path),
        ),
    ]
