# Generated by Django 3.1.7 on 2021-07-30 06:51

import assignment.models
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_alter_submissionmodel_sub_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionmodel',
            name='sub_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/submission', location='/Users/LeeJunYoung/Desktop/NESPA/data/submission'), upload_to=assignment.models.submission_upload_path),
        ),
        migrations.CreateModel(
            name='GradeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_input', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/assignment', location='/Users/LeeJunYoung/Desktop/NESPA/data/problems'), upload_to=assignment.models.grade_data_upload_path)),
                ('grade_output', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/assignment', location='/Users/LeeJunYoung/Desktop/NESPA/data/problems'), upload_to=assignment.models.grade_data_upload_path)),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.problemmodel')),
            ],
        ),
    ]
