# Generated by Django 3.0.8 on 2020-09-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_auto_20200914_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionmodel',
            name='lang',
            field=models.CharField(default='cpp', max_length=20),
            preserve_default=False,
        ),
    ]
