# Generated by Django 3.1.7 on 2021-07-30 16:26

import assignment.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0010_auto_20210730_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemmodel',
            name='header_data',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/assignment', location='/Users/LeeJunYoung/Desktop/NESPA/data/assignment'), upload_to=assignment.models.sample_data_upload_path),
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='sub_data',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/assignment', location='/Users/LeeJunYoung/Desktop/NESPA/data/assignment'), upload_to=assignment.models.sample_data_upload_path),
        ),
    ]
