# Generated by Django 3.1 on 2020-09-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0010_submissionmodel_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionmodel',
            name='prob_name',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
