# Generated by Django 3.2.5 on 2021-08-09 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0013_auto_20210802_1359'),
        ('assignment', '0013_auto_20210803_2106'),
    ]

    operations = [
    ]
