# Generated by Django 3.2.5 on 2021-08-10 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0014_auto_20210809_1635'),
        ('assignment', '0014_merge_0013_auto_20210802_1359_0013_auto_20210803_2106'),
    ]

    operations = [
    ]
